package main;

import util.DatabaseUtil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;

public class GetAutoGeneratedPrimaryKey {
    public static void main(String[] args) {
        String query = "insert into employee(employee_name, employee_salary, employee_dept, employee_dob) values (?, ?, ?, ?)";

        try(
                Connection connection = DatabaseUtil.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                ){

            preparedStatement.setString(1, "Pollobi");
            preparedStatement.setDouble(2, 36000);
            preparedStatement.setString(3, "Business Development");
            preparedStatement.setObject(4, LocalDate.of(2006, 5, 13));
            preparedStatement.executeUpdate();

            ResultSet resultSet  = preparedStatement.getGeneratedKeys();
            if(resultSet.next()){
                System.out.println("Employee is created with ID = " + resultSet.getInt(1));
            }

        }catch (Exception e){
            e.printStackTrace();
        }
    }
}
